Starting Etcd Service before configuring it.
To resolve the following error, we need to start the Etcd service first.

$ etcdctl mkdir /kube-centos/network
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused